import { User, Post } from './types';

export const users: User[] = [
    {
        id: 'u1',
        username: 'alice',
        name: 'Alice Smith',
        bio: 'Coffee lover. Cat person.',
        avatar_url: 'https://randomuser.me/api/portraits/women/1.jpg',
    },
    {
        id: 'u2',
        username: 'bob',
        name: 'Bob Johnson',
        bio: 'Full-stack dev & gamer.',
        avatar_url: 'https://randomuser.me/api/portraits/men/2.jpg',
    },
    {
        id: 'u3',
        username: 'carol',
        name: 'Carol Lee',
        bio: 'Photographer & traveler.',
        avatar_url: 'https://randomuser.me/api/portraits/women/3.jpg',
    },
    {
        id: 'u4',
        username: 'dan',
        name: 'Dan Brown',
        bio: 'Writer. Dreamer.',
        avatar_url: 'https://randomuser.me/api/portraits/men/4.jpg',
    },
    {
        id: 'u5',
        username: 'eve',
        name: 'Eve Adams',
        bio: 'Tech enthusiast.',
        avatar_url: 'https://randomuser.me/api/portraits/women/5.jpg',
    },
];

// Helper to get user by id
const getUser = (id: string) => users.find(u => u.id === id)!;

export const posts: Post[] = [
    {
        id: 'p1',
        content: 'This is my first post! I finally figured out how to turn on my computer. Next step: world domination.',
        created_at: new Date('2024-06-01T10:00:00Z'),
        authorId: 'u1',
        user: getUser('u1'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p2',
        content: 'Here are some tips for React Native development: 1) Don’t forget to shake your phone, it’s not mad at you. 2) If it doesn’t work, try turning it off and on again. 3) Coffee helps.',
        created_at: new Date('2025-06-01T11:00:00Z'),
        authorId: 'u2',
        user: getUser('u2'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p3',
        content: 'Just got back from Japan! Ate sushi, saw Mt. Fuji, and accidentally joined a sumo wrestling class. 10/10 would recommend.',
        created_at: new Date('2024-06-01T12:00:00Z'),
        authorId: 'u3',
        user: getUser('u3'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p4',
        content: 'Check out these amazing books: "How to Survive Without WiFi", "JavaScript for Cats", and "The Art of Procrastination".',
        created_at: new Date('2025-06-01T13:00:00Z'),
        authorId: 'u4',
        user: getUser('u4'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p5',
        content: 'Latest updates in tech: AI is taking over, robots are learning to dance, and my toaster just asked for a software update.',
        created_at: new Date('2025-06-01T14:00:00Z'),
        authorId: 'u5',
        user: getUser('u5'),
        parentId: null,
        parent: null,
        replies: [],
    },
    // Replies to p1
    {
        id: 'p6',
        content: 'Welcome to the platform! Don’t worry, we all started by accidentally liking our own posts.',
        created_at: new Date('2024-06-01T15:00:00Z'),
        authorId: 'u2',
        user: getUser('u2'),
        parentId: 'p1',
        parent: null,
        replies: [],
    },
    {
        id: 'p7',
        content: 'Nice to see you here! Pro tip: If you break something, just blame it on the intern.',
        created_at: new Date('2025-06-01T15:05:00Z'),
        authorId: 'u3',
        user: getUser('u3'),
        parentId: 'p1',
        parent: null,
        replies: [],
    },
    // Replies to p2
    {
        id: 'p8',
        content: 'Thanks for the tips! I tried shaking my phone and now my cat thinks it’s a toy.',
        created_at: new Date('2024-06-01T16:00:00Z'),
        authorId: 'u1',
        user: getUser('u1'),
        parentId: 'p2',
        parent: null,
        replies: [],
    },
    {
        id: 'p9',
        content: 'Very helpful. Also, is there a React Native tip for making coffee?',
        created_at: new Date('2024-06-01T16:10:00Z'),
        authorId: 'u5',
        user: getUser('u5'),
        parentId: 'p2',
        parent: null,
        replies: [],
    },
    // Replies to p3
    {
        id: 'p10',
        content: 'Japan is on my bucket list! Did you try karaoke? I hear it’s a rite of passage.',
        created_at: new Date('2025-06-01T17:00:00Z'),
        authorId: 'u4',
        user: getUser('u4'),
        parentId: 'p3',
        parent: null,
        replies: [],
    },
    // Replies to p6 (nested reply)
    {
        id: 'p11',
        content: 'Thank you! I’ll try not to break the internet (again).',
        created_at: new Date('2024-06-01T17:10:00Z'),
        authorId: 'u1',
        user: getUser('u1'),
        parentId: 'p6',
        parent: null,
        replies: [],
    },
    // More top-level posts
    {
        id: 'p12',
        content: 'How to take better photos: 1) Clean your lens. 2) Don’t drop your camera. 3) If all else fails, add a filter and call it "artsy".',
        created_at: new Date('2025-06-01T18:00:00Z'),
        authorId: 'u3',
        user: getUser('u3'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p13',
        content: 'What are your favorite movies? Mine is "Debugging: The Movie". It’s a real thriller.',
        created_at: new Date('2024-06-01T19:00:00Z'),
        authorId: 'u4',
        user: getUser('u4'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p14',
        content: 'Share your best healthy recipes! Bonus points if it involves chocolate and zero effort.',
        created_at: new Date('2025-06-01T20:00:00Z'),
        authorId: 'u5',
        user: getUser('u5'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p15',
        content: 'What are you doing this weekend? I’m planning to nap so hard I wake up in a different timezone.',
        created_at: new Date('2025-06-01T21:00:00Z'),
        authorId: 'u2',
        user: getUser('u2'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p16',
        content: 'My cat just tried to code by walking across my keyboard. Now my project won’t compile, but at least it purrs.',
        created_at: new Date('2024-06-01T22:00:00Z'),
        authorId: 'u1',
        user: getUser('u1'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p17',
        content: 'Serious debate: Coffee or tea? I tried both at once and now I can see sounds.',
        created_at: new Date('2024-06-01T22:30:00Z'),
        authorId: 'u2',
        user: getUser('u2'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p18',
        content: 'What’s on your coding playlist? Mine is just the sound of my computer fan and existential dread.',
        created_at: new Date('2024-06-01T23:00:00Z'),
        authorId: 'u3',
        user: getUser('u3'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p19',
        content: 'If you could go anywhere, where would you go? I’d go to a land where bugs fix themselves.',
        created_at: new Date('2024-06-01T23:30:00Z'),
        authorId: 'u4',
        user: getUser('u4'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p20',
        content: 'It’s 2am and my code finally works. I have no idea why, but I’m not touching anything.',
        created_at: new Date('2025-03-02T00:00:00Z'),
        authorId: 'u5',
        user: getUser('u5'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p21',
        content: 'Pitch your wildest app idea! Mine is an app that reminds you to stop checking your phone.',
        created_at: new Date('2024-06-02T00:30:00Z'),
        authorId: 'u1',
        user: getUser('u1'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p22',
        content: 'Unpopular opinion: Tabs are better than spaces. Fight me (gently, with words).',
        created_at: new Date('2024-06-02T01:00:00Z'),
        authorId: 'u2',
        user: getUser('u2'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p23',
        content: 'My morning routine: Wake up, hit snooze, dream about breakfast, finally get up when my cat sits on my face.',
        created_at: new Date('2024-06-02T01:30:00Z'),
        authorId: 'u3',
        user: getUser('u3'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p24',
        content: 'Last night I dreamed my code compiled on the first try. Wild, right?',
        created_at: new Date('2024-06-02T02:00:00Z'),
        authorId: 'u4',
        user: getUser('u4'),
        parentId: null,
        parent: null,
        replies: [],
    },
    {
        id: 'p25',
        content: 'Life hack: If you can’t find your keys, check the fridge. If you find cheese, you’re in the right place.',
        created_at: new Date('2024-06-02T02:30:00Z'),
        authorId: 'u5',
        user: getUser('u5'),
        parentId: null,
        parent: null,
        replies: [],
    },
];

// Set parent and replies relationships
const postMap: { [id: string]: Post } = {};
posts.forEach(post => postMap[post.id] = post);

posts.forEach(post => {
        if (post.parentId) {
            post.parent = postMap[post.parentId];
            postMap[post.parentId].replies.push(post);
        }
    }
)